package com.breskeby.gradle.site

/**
 * Created by IntelliJ IDEA.
 * @author: Rene
 */

import groovy.xml.MarkupBuilder
import java.text.DateFormat
import org.gradle.util.GradleVersion

class DefaultSiteRenderer {

    MarkupBuilder builder;

    final SiteModel model;

    public DefaultSiteRenderer(SiteModel model) {
        this.model = model
    }

    void render(File outputFile, String contentString = "") {
        OutputStream outputStream = new FileOutputStream(outputFile);

        try {
            PrintWriter writer = new PrintWriter(new OutputStreamWriter(outputStream, "utf-8"));

            writer.println('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">');
            builder = new MarkupBuilder(new IndentPrinter(writer, ""));

            //TODO just to initialize SiteModel
            model.headerTitle

            builder.html {
                head {
                    meta('http-equiv': "Content-Type", content: "text/html; charset=UTF-8")
                    title(model.title)
                    link(rel: 'stylesheet', href: 'maven-base.css', type: 'text/css')
                    link(rel: 'stylesheet', href: 'maven-theme.css', type: 'text/css')
                    script(src: 'report.js', type: 'text/javascript', " ")
                }
                body {
                    div(id:'banner'){

                        div(id:'bannerLeft', "${model.project.name}") {

                        }

                        a(href:"${model.bannerRightHref}", id:'bannerRight'){
                           img(src:"${model.bannerRightSrc}", alt:"${model.bannerRightAlt}"){

                           }
                        }

                        div(class:"clear", '<hr>')
                    }

                    div(id: "breadcrumbs") {
                        div(class:"xleft") {
                            span(id:"publishDate", "Last Published: right now")
                        }
                        div(class:"xright", "")

                        div(class:"clear", '<hr>')
                    }

                    div(id: "leftColumn") {
                        div(id: "navcolumn") {
                            model.menu.each { section, items ->
                                h5(section)
                                ul {
                                    items.each { item, link ->
                                        li(class: "none") {
                                            a(href: link, item)
                                        }
                                    }
                                }
                            }
                        }
                    }
                    div(id:'bodyColumn'){
                        div(id:'contentBox'){
                            renderContent()
                        }
                    }

                    div(id: 'footer') {
                        p {
                            mkp.yield('Generated by ')
                            a(href: 'http://www.gradle.org', "Gradle ${GradleVersion.current().version}")
                            mkp.yield(" at ${DateFormat.getDateTimeInstance().format(new Date())}")
                        }
                    }
                }
            }
            writer.flush();
        } finally {
            outputStream.close();
        }

    }

    protected void renderContent(){

    }
}




